version: '3.8'

services:
  backend:
    build: ./backend
    container_name: malis_backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=postgresql://user:password@db:5432/logistics
    depends_on:
      - ollama
      - db
    volumes:
      - ./backend/app:/code/app

  db:
    image: postgres:15-alpine
    container_name: malis_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=logistics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: malis_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data: