version: '3.8'

services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: mock_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"

    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # 2. The Ollama AI Engine
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # GPU Support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # 3. The LangGraph Backend
  backend:
    build: ./backend
    container_name: sql_agent_backend
    environment:
      - PYTHONUNBUFFERED=1  # <--- ADD THIS
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    # For testing, remove for production
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: sql_agent_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app         # Syncs your live code
      - /app/node_modules

volumes:
  ollama_data: